spring.application.name=first-job-app
server.port=8085
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

info.app.name=firstjavascringbootjobapplication
info.app.description=First java spring boot job application
info.app.version=1.0.0

management.info.env.enabled= true
#management.endpoint.shutdown.enabled=true
#server.shutdown=graceful
